(()=>{"use strict";
const GAMES=[...(window.GAMES_A||[]),...(window.GAMES_B||[])];
const IDS=window.KNOWN_APP_IDS||{};
const CAPS=window.GAME_CAPABILITIES||{};
const $=id=>document.getElementById(id);
const pick=$("pick"),result=$("result"),gameName=$("gameName"),status=$("status"),steamLink=$("steamLink"),searchLink=$("searchLink"),meta=$("meta"),cover=$("cover"),coverWrap=$("coverWrap"),genreFact=$("genreFact"),modeFact=$("modeFact"),playersFact=$("playersFact"),modeFilter=$("modeFilter"),noRepeat=$("noRepeat"),poolInfo=$("poolInfo"),historyCount=$("historyCount"),historyList=$("historyList"),historyEmpty=$("historyEmpty"),resetUsed=$("resetUsed"),clearHistory=$("clearHistory");
const KEYS={resolved:"steam-family-randomizer-cache-v3",details:"steam-family-randomizer-details-v1",history:"steam-family-randomizer-history-v1",used:"steam-family-randomizer-used-v1",settings:"steam-family-randomizer-settings-v1"};
let last=-1,resolved={},details={},history=[],used=new Set(),settings={filter:"all",noRepeat:false};
function load(){try{resolved=JSON.parse(localStorage.getItem(KEYS.resolved)||"{}")||{}}catch{}try{details=JSON.parse(localStorage.getItem(KEYS.details)||"{}")||{}}catch{}try{history=JSON.parse(localStorage.getItem(KEYS.history)||"[]")||[]}catch{}try{used=new Set(JSON.parse(localStorage.getItem(KEYS.used)||"[]")||[])}catch{}try{settings={...settings,...(JSON.parse(localStorage.getItem(KEYS.settings)||"{}")||{})}}catch{}modeFilter.value=settings.filter||"all";noRepeat.checked=!!settings.noRepeat}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const saveResolved=()=>save(KEYS.resolved,resolved),saveDetails=()=>save(KEYS.details,details),saveHistory=()=>save(KEYS.history,history),saveUsed=()=>save(KEYS.used,[...used]),saveSettings=()=>save(KEYS.settings,{filter:modeFilter.value,noRepeat:noRepeat.checked});
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[™®©]/g,"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," "),compact=s=>norm(s).replace(/\s+/g,"");
function tokenScore(a,b){const A=new Set(norm(a).split(" ").filter(Boolean)),B=new Set(norm(b).split(" ").filter(Boolean));if(!A.size||!B.size)return 0;let i=0;for(const x of A)if(B.has(x))i++;return i/(A.size+B.size-i)}
function bigrams(s){s=compact(s);if(!s)return[];if(s.length<2)return[s];const o=[];for(let i=0;i<s.length-1;i++)o.push(s.slice(i,i+2));return o}
function dice(a,b){const A=bigrams(a),B=bigrams(b);if(!A.length||!B.length)return 0;const c=new Map;for(const x of A)c.set(x,(c.get(x)||0)+1);let i=0;for(const x of B){const n=c.get(x)||0;if(n){i++;c.set(x,n-1)}}return 2*i/(A.length+B.length)}
function score(q,c){const a=norm(q),b=norm(c);if(!a||!b)return 0;if(a===b||compact(q)===compact(c))return 1;let s=tokenScore(q,c)*.58+dice(q,c)*.34+(a.startsWith(b)||b.startsWith(a)?.08:0);const an=a.match(/\b\d+\b/g)||[],bn=b.match(/\b\d+\b/g)||[];if(an.join(",")!==bn.join(","))s-=.18;for(const w of["legacy","remastered","definitive","enhanced","vr","test","beta","multiplayer","goty"])if(a.includes(w)!==b.includes(w))s-=.06;return Math.max(0,Math.min(1,s))}
function collect(p){const out=[],seen=new Set;function walk(n,d=0){if(d>7||n==null)return;if(Array.isArray(n)){for(const x of n)walk(x,d+1);return}if(typeof n!=="object")return;const id=n.appId??n.appid??n.steam_appid??n.id,name=n.gameName??n.name??n.title??n.displayName,image=n.gameImage??n.image??n.capsule??n.header_image??null;if(/^\d+$/.test(String(id||""))&&typeof name==="string"&&name.trim()&&!seen.has(String(id))){seen.add(String(id));out.push({appid:Number(id),name:name.trim(),image})}for(const v of Object.values(n))if(v&&typeof v==="object")walk(v,d+1)}walk(p);return out}
const direct=id=>"https://store.steampowered.com/app/"+encodeURIComponent(String(id))+"/",search=n=>"https://store.steampowered.com/search/?term="+encodeURIComponent(n),cdn=id=>"https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/"+encodeURIComponent(String(id))+"/header.jpg";
function clearLinks(){steamLink.classList.add("hidden");searchLink.classList.add("hidden");meta.textContent=""}
function setFact(el,text){if(text){el.textContent=text;el.classList.remove("hidden")}else{el.textContent="";el.classList.add("hidden")}}
function resetCover(){coverWrap.classList.remove("show");cover.removeAttribute("src");cover.alt=""}
function setCover(name,appid,image){resetCover();if(!appid&&!image)return;let fallbackUsed=false;cover.alt="Portada de "+name;cover.onload=()=>coverWrap.classList.add("show");cover.onerror=()=>{if(!fallbackUsed&&appid){fallbackUsed=true;cover.src="https://cdn.akamai.steamstatic.com/steam/apps/"+appid+"/header.jpg"}else resetCover()};cover.src=image||cdn(appid)}
function showDirect(n,id,canonical,source,image){steamLink.href=direct(id);steamLink.classList.remove("hidden");searchLink.classList.add("hidden");status.innerHTML='<span class="dot"></span>Enlace directo de Steam listo.';meta.textContent="App ID "+id+(canonical&&norm(canonical)!==norm(n)?" · Steam: "+canonical:"")+(source==="cache"?" · guardado en este navegador":"");setCover(n,id,image)}
function fallback(n,d){searchLink.href=search(n);searchLink.classList.remove("hidden");steamLink.classList.add("hidden");status.innerHTML='<span class="dot warn"></span>No encontré una coincidencia suficientemente segura para enlazar automáticamente.';meta.textContent=d||"Puede ser una beta, Test Server, app retirada o edición especial."}
function staticMeta(name){return CAPS[name]||{}}
function modeLabels(m=[]){const labels=[];if(m.includes("coop"))labels.push("Co-op");if(m.includes("multi"))labels.push("Multijugador");return labels.join(" · ")}
function tagsToModes(tags=[]){const t=tags.map(x=>norm(x)),coop=t.some(x=>x.includes("co op")||x.includes("coop")),multi=coop||t.some(x=>x==="multiplayer"||x.includes("pvp")||x.includes("massively multiplayer"));return[...(coop?["coop"]:[]),...(multi?["multi"]:[])]}
function mergedMeta(name){const s=staticMeta(name),d=details[name]||{},tags=Array.isArray(d.tags)?d.tags:[],dynModes=tagsToModes(tags),modes=[...new Set([...(s.m||[]),...dynModes])],party4=!!s.party4||tags.some(x=>norm(x)==="4 player local");return{genre:d.genre||s.genre||"",players:s.players||d.players||"",modes,party4,tags,developer:d.developer||""}}
function renderFacts(name){const d=mergedMeta(name);setFact(genreFact,d.genre?"🎮 "+d.genre.split(",").slice(0,3).join(" · "):"");setFact(modeFact,d.modes.length?"👥 "+modeLabels(d.modes):"");setFact(playersFact,d.players?"🎯 "+d.players+" jugadores":d.party4?"🎯 Apto para 4":"")}
function qualifies(name,filter){if(filter==="all")return true;const d=mergedMeta(name);if(filter==="multi")return d.modes.includes("multi")||d.modes.includes("coop");if(filter==="coop")return d.modes.includes("coop");if(filter==="four")return d.party4;return true}
function basePool(){return GAMES.filter(n=>qualifies(n,modeFilter.value))}
function currentPool(){let p=basePool();if(noRepeat.checked)p=p.filter(n=>!used.has(n));return p}
function updatePoolInfo(){const base=basePool(),available=currentPool(),learned=Object.keys(details).length;if(modeFilter.value==="all")poolInfo.textContent=noRepeat.checked?available.length+" disponibles sin repetir de "+base.length:base.length+" juegos disponibles.";else poolInfo.textContent=available.length+" candidatos confirmados para este filtro"+(noRepeat.checked?" sin repetir":"")+" · "+learned+" juegos con metadatos aprendidos."}
function renderHistory(){historyCount.textContent=history.length;historyList.innerHTML="";historyEmpty.classList.toggle("hidden",history.length>0);for(const item of history.slice(0,20)){const li=document.createElement("li"),d=new Date(item.ts);li.textContent=item.name+" — "+d.toLocaleString("es-CR",{dateStyle:"short",timeStyle:"short"});historyList.appendChild(li)}}
function addHistory(name){history.unshift({name,ts:Date.now()});history=history.slice(0,60);saveHistory();renderHistory()}
async function fetchExtra(name,appid){if(!appid||details[name]?.checked)return;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),3500);try{const r=await fetch("https://steamspy.com/api.php?request=appdetails&appid="+encodeURIComponent(appid),{signal:controller.signal});if(!r.ok)throw Error("HTTP "+r.status);const x=await r.json(),tags=x&&typeof x.tags==="object"&&!Array.isArray(x.tags)?Object.keys(x.tags):[];details[name]={checked:true,genre:String(x.genre||""),tags,developer:String(x.developer||"")}}catch(e){details[name]={...(details[name]||{}),checked:true}}finally{clearTimeout(timer);saveDetails();renderFacts(name);updatePoolInfo()}}
async function resolve(n){clearLinks();resetCover();if(IDS[n]){resolved[n]={appid:IDS[n],name:n};saveResolved();showDirect(n,IDS[n],n,"seed");fetchExtra(n,IDS[n]);return IDS[n]}if(resolved[n]?.appid){showDirect(n,resolved[n].appid,resolved[n].name||n,"cache",resolved[n].image);fetchExtra(n,resolved[n].appid);return resolved[n].appid}status.textContent="Buscando la ficha exacta en Steam…";try{const r=await fetch("https://steamtools.games/api/search?query="+encodeURIComponent(n),{headers:{Accept:"application/json"}});if(!r.ok)throw Error("HTTP "+r.status);const cand=collect(await r.json());let best=null;for(const x of cand){const s=score(n,x.name);if(!best||s>best.score)best={...x,score:s}}const exact=best&&(norm(best.name)===norm(n)||compact(best.name)===compact(n)),threshold=norm(n).length<=5?.95:.78;if(best&&(exact||best.score>=threshold)){resolved[n]={appid:best.appid,name:best.name,image:best.image||null};saveResolved();showDirect(n,best.appid,best.name,"live",best.image);fetchExtra(n,best.appid);return best.appid}fallback(n,best?'La coincidencia más cercana fue "'+best.name+'" ('+Math.round(best.score*100)+' %); la descarté para evitar un enlace equivocado.':"El catálogo no devolvió una ficha pública.")}catch(e){fallback(n,"No se pudo consultar el catálogo ahora mismo. "+(e?.message||""))}return null}
function rand(max){if(max<1)return-1;if(globalThis.crypto&&crypto.getRandomValues){const lim=Math.floor(4294967296/max)*max,a=new Uint32Array(1);let n;do{crypto.getRandomValues(a);n=a[0]}while(n>=lim);return n%max}return Math.floor(Math.random()*max)}
async function choose(){pick.disabled=true;let pool=currentPool();if(!pool.length&&noRepeat.checked&&basePool().length){used.clear();saveUsed();pool=currentPool();poolInfo.textContent="La bolsa se agotó y se reinició automáticamente."}if(!pool.length){status.textContent="No hay juegos confirmados para este filtro todavía.";result.classList.add("show");gameName.textContent="Sin candidatos";clearLinks();resetCover();setFact(genreFact,"");setFact(modeFact,"");setFact(playersFact,"");pick.disabled=false;return}let i=rand(pool.length),n=pool[i];if(pool.length>1){while(n===GAMES[last]){i=rand(pool.length);n=pool[i]}}last=GAMES.indexOf(n);gameName.textContent=n;result.classList.add("show");renderFacts(n);if(noRepeat.checked){used.add(n);saveUsed()}addHistory(n);updatePoolInfo();await resolve(n);pick.textContent="🎲 ELEGIR OTRO JUEGO";pick.disabled=false}
modeFilter.addEventListener("change",()=>{saveSettings();updatePoolInfo()});noRepeat.addEventListener("change",()=>{saveSettings();updatePoolInfo()});resetUsed.addEventListener("click",()=>{used.clear();saveUsed();updatePoolInfo();resetUsed.textContent="Bolsa reiniciada ✓";setTimeout(()=>resetUsed.textContent="Reiniciar bolsa de no repetidos",1200)});clearHistory.addEventListener("click",()=>{history=[];saveHistory();renderHistory()});pick.addEventListener("click",choose);
load();renderHistory();updatePoolInfo();if(GAMES.length!==1061){pick.disabled=true;pick.textContent="Base de datos incompleta";poolInfo.textContent="Error: se esperaban 1.061 entradas y se cargaron "+GAMES.length+"."}
})();